version: '2'
services:

  zookeeper0:
    container_name: zookeeper0
    image: confluentinc/cp-zookeeper
    environment:
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka0:
    container_name: kafka0
    image: confluentinc/cp-kafka
    environment:
      KAFKA_REPLICA_FETCH_MAX_BYTES:  33554432
      KAFKA_MESSAGE_MAX_BYTES: 33554432
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper0:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
    ports:
      - 9092:9092
    depends_on:
      - zookeeper0
