server:
  port: 8083
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/loggerapi
    username: loggerapi
    password: loggerapi
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
kafka:
  bootstrapServers: localhost:9092 # Development Kafka brokers
  #  bootstrapServers: localhost:19092;localhost:29092;localhost:39092 # Production Kafka Brokers
  topic:
    blockchain: blockchain-logger-topic
  consumer:
    groupId: logger
    autoOffsetReset: earliest
    maxPollRecords: 1
    enableAutoCommit: false
    fetchMaxBytes: 33554432