server:
  port: 8081
swarm:
  value: swarmClient
  url: http://localhost:8501/bzz
kafka:
  bootstrapServers: localhost:9092
  topic:
    video: video-distributed-storage-topic
    blockchain: distributed-storage-blockchain-topic
  producer:
    acks: all
    retries: 0
    batchSize: 16384
    lingerMs: 1
    bufferMemory: 33554432
    maxRequestSize: 33554432
  consumer:
    groupId: swarm
    autoOffsetReset: earliest
    maxPollRecords: 1
    enableAutoCommit: false
    fetchMaxBytes: 33554432