spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 800MB
      max-request-size: 815MB
swarm:
  value: swarmClient
  url: http://localhost:8501/bzz
kafka:
  #  bootstrapServers: localhost:9092 # Development Kafka brokers
  bootstrapServers: localhost:19092;localhost:29092;localhost:39092 # Production Kafka brokers
  topic:
    blockchain: distributed-storage-blockchain-topic
  producer:
    acks: all
    retries: 0
    batchSize: 16384
    lingerMs: 1
    bufferMemory: 90000000
    maxRequestSize: 90000000