version: '2'

services:
  zookeeper-base:
    image: confluentinc/cp-zookeeper:$IMAGE_TAG
    environment:
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2

  kafka-base:
    image: confluentinc/cp-kafka:$IMAGE_TAG
    environment:
      KAFKA_REPLICA_FETCH_MAX_BYTES:  33554432
      KAFKA_MESSAGE_MAX_BYTES: 33554432
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1