version: '2'
services:

  zookeeper0:
    container_name: zookeeper0
    extends:
      file: base/kafka-base.yaml
      service: zookeeper-base
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka0:
    container_name: kafka0
    extends:
      file: base/kafka-base.yaml
      service: kafka-base
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper0:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
    ports:
      - 9092:9092
    depends_on:
      - zookeeper0