spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 800MB
      max-request-size: 815MB
kafka:
#  bootstrapServers: localhost:9092 # Development Kafka brokers
  bootstrapServers: localhost:19092;localhost:29092;localhost:39092 # Production Kafka Brokers
  topic:
    blockchain: distributed-storage-blockchain-topic
  producer:
    acks: all
    retries: 0
    batchSize: 16384
    lingerMs: 1
    bufferMemory: 90000000
    maxRequestSize: 90000000
ipfs:
  url: /ip4/127.0.0.1/tcp/5001