server:
  port: 8081
kafka:
  bootstrapServers: localhost:9092
  topic:
    video: video-distributed-storage-topic
    blockchain: distributed-storage-blockchain-topic
  producer:
    acks: all
    retries: 0
    batchSize: 16384
    lingerMs: 1
    bufferMemory: 33554432
    maxRequestSize: 33554432
  consumer:
    groupId: ipfs
    autoOffsetReset: earliest
    maxPollRecords: 1
    enableAutoCommit: false
    fetchMaxBytes: 33554432
ipfs:
  url: /ip4/127.0.0.1/tcp/5001