server:
  port: 8082
kafka:
  bootstrapServers: localhost:9092
  topic:
    distributedStorage: distributed-storage-blockchain-topic
    logger: blockchain-logger-topic
  producer:
    acks: all
    retries: 0
    batchSize: 16384
    lingerMs: 1
    bufferMemory: 33554432
    maxRequestSize: 33554432
  consumer:
    groupId: fabric
    autoOffsetReset: earliest
    maxPollRecords: 1
    enableAutoCommit: false
    fetchMaxBytes: 33554432
bigchaindb:
  peer0:
    url: http://localhost:32845
  peer1:
    url: http://localhost:32923
  peer2:
    url: http://localhost:32929
  peer3:
    url: http://localhost:32935
  keyPair:
    directoryPath: src/main/resources/keypair
    privateKeyFileName: privateKey.key