spring:
  data:
    mongodb:
      host: localhost
      port: 32769
      database: bigchain
server:
  port: 8081
kafka:
  #  bootstrapServers: localhost:9092 # Development Kafka brokers
  bootstrapServers: localhost:19092;localhost:29092;localhost:39092 # Production Kafka brokers
  topic:
    distributedStorage: distributed-storage-blockchain-topic
  consumer:
    groupId: fabric
    autoOffsetReset: earliest
    maxPollRecords: 1
    enableAutoCommit: false
    fetchMaxBytes: 90000000
bigchaindb:
  peer0:
    url: http://localhost:32797
  peer1:
    url: http://localhost:32803
  peer2:
    url: http://localhost:32809
  peer3:
    url: http://localhost:32815
  keyPair:
    directoryPath: src/main/resources/keypair
    privateKeyFileName: privateKey.key
swarm:
  value: blockchain-swarm-client
  url: http://localhost:8501/bzz
ipfs:
  url: /ip4/127.0.0.1/tcp/5001
logger:
  value: logger-client
  url: https://heroku-logger-api.herokuapp.com/
