spring:
  data:
    mongodb:
      host: localhost
      port: 32841
      database: bigchain
server:
  port: 8082
kafka:
  bootstrapServers: localhost:9092 # Development Kafka brokers
  #  bootstrapServers: localhost:19092;localhost:29092;localhost:39092 # Production Kafka brokers
  topic:
    distributedStorage: distributed-storage-blockchain-topic
    logger: blockchain-logger-topic
  producer:
    acks: all
    retries: 0
    batchSize: 16384
    lingerMs: 1
    bufferMemory: 33554432
    maxRequestSize: 33554432
  consumer:
    groupId: fabric
    autoOffsetReset: earliest
    maxPollRecords: 1
    enableAutoCommit: false
    fetchMaxBytes: 33554432
bigchaindb:
  peer0:
    url: http://localhost:32869
  peer1:
    url: http://localhost:32875
  peer2:
    url: http://localhost:32881
  peer3:
    url: http://localhost:32887
  keyPair:
    directoryPath: src/main/resources/keypair
    privateKeyFileName: privateKey.key
swarm:
  value: blockchain-swarm-client
  url: http://localhost:8501/bzz
ipfs:
  url: /ip4/127.0.0.1/tcp/5001