# KAFKA PROPERTIES
kafka:
  bootstrapServers: localhost:9092
  topic: producer-topic
  consumer:
    groupId: group-id
    autoOffsetReset: earliest
    maxPollRecords: 1
    enableAutoCommit: false
    fetchMaxBytes: 33554432
  producer:
    acks: all
    retries: 0
    batchSize: 16384
    lingerMs: 1
    bufferMemory: 33554432
    maxRequestSize: 33554432

# BIGCHAINDB PROPERTIES
bigchaindb:
  peer0:
    url: http://localhost:9984
  peer1:
    url: http://localhost:33199
  peer2:
    url: http://localhost:33205
  peer3:
    url: http://localhost:33211
  keyPair:
    directoryPath: src/main/resources/keypair
    privateKeyFileName: privateKey.key

# SWARM PROPERTIES
swarm:
  value: swarmClient
  url: http://localhost:8501/bzz

# MOCKED FILE PATH
default.video.path: /home/eduardo/Downloads/video.mp4

