# KAFKA PROPERTIES
kafka:
  bootstrapServers: localhost:9092
  topic: producer-topic
  consumer:
    groupId: group-id
    autoOffsetReset: earliest
    maxPollRecords: 1
    enableAutoCommit: false
    fetchMaxBytes: 33554432
  producer:
    acks: all
    retries: 0
    batchSize: 16384
    lingerMs: 1
    bufferMemory: 33554432
    maxRequestSize: 33554432

# IPFS PROPERTIES
ipfs:
  url: /ip4/127.0.0.1/tcp/5001