version: '2'

services:
  bigchaindb.example.com:
    image: bigchaindb/bigchaindb:all-in-one
    container_name: bigchaindb.example.com
    volumes:
      - $HOME/docker/volumes/bigchaindb/mongodb/data/db:/data/db
      - $HOME/docker/volumes/bigchaindb/mongodb/data/configdb:/data/configdb
      - $HOME/docker/volumes/bigchaindb/tendermint:/tendermint
    ports:
      - 9984:9984
      - 9985:9985
      - 27017:27017
      - 26657:26657