spring:
  main:
    allow-bean-definition-overriding: true
server:
  port: 8082
kafka:
  bootstrapServers: localhost:9092 # Development Kafka brokers
  #  bootstrapServers: localhost:19092;localhost:29092;localhost:39092 # Production Kafka Brokers
  topic:
    distributedStorage: distributed-storage-blockchain-topic
    logger: blockchain-logger-topic
  producer:
    acks: all
    retries: 0
    batchSize: 16384
    lingerMs: 1
    bufferMemory: 33554432
    maxRequestSize: 33554432
  consumer:
    groupId: fabric
    autoOffsetReset: earliest
    maxPollRecords: 1
    enableAutoCommit: false
    fetchMaxBytes: 33554432
fabric:
  admin:
    username: admin
    password: adminpw
  ca:
    org1:
      url: http://localhost:7054
  orderer:
    url: grpc://localhost:7050
    name: orderer.example.com
  channel:
    name: mychannel
  org1:
    name: org1
    msp: Org1MSP
    peer0:
      name: peer0.org1.example.com
      url: grpc://localhost:7051
    peer1:
      name: peer1.org1.example.com
      url: grpc://localhost:8051
    peer2:
      name: peer2.org1.example.com
      url: grpc://localhost:9051
    peer3:
      name: peer3.org1.example.com
      url: grpc://localhost:10051
  userDirectoryPath: src/main/resources/user
swarm:
  value: blockchain-swarm-client
  url: http://localhost:8501/bzz
ipfs:
  url: /ip4/127.0.0.1/tcp/5001
