spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 215MB
kafka:
# bootstrapServers: localhost:9092 # Development Kafka brokers
  bootstrapServers: localhost:19092;localhost:29092;localhost:39092 # Production Kafka brokers
  topic:
    distributedStorage: video-distributed-storage-topic
  producer:
    acks: all
    retries: 0
    batchSize: 16384
    lingerMs: 1
    bufferMemory: 33554432
    maxRequestSize: 33554432
feign:
  blockchain:
    value: blockchainClient
    url: http://localhost:8082/api